#!/bin/bash
exec 2>&1

set -x

{{#if bind.database.first.cfg.host }}
HOSTNAME="{{bind.database.first.cfg.host}}" # database.host
{{else }}
HOSTNAME="{{bind.database.first.sys.ip}}" # sys.ip
{{/if }}

# check if database exists
mysql_ready() {
    mysqladmin ping -h $HOSTNAME -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} > /dev/null 2>&1
}

if !(mysql_ready) then
   echo "waiting for mysql ..."
   exit 1
fi

# create database
mysql -h $HOSTNAME -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -e "create database IF NOT EXISTS {{bind.database.first.cfg.database}}"

# restore initial database if not present
{{#unless cfg.nodbrestore ~}}
if !(mysqlshow -h 127.0.0.1 wordpress | grep -q wp) then
  mysql -h $HOSTNAME -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} wordpress < {{pkg.svc_config_path}}/wordpress-4.9.9-initial.sql
fi
{{/unless ~}}

cp -r {{pkg.path}}/wordpress/* {{pkg.svc_data_path}}
cp -n {{pkg.svc_config_path}}/wp-config.php {{pkg.svc_data_path}}

# rename file so we can use fpm default
cp -n {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf.default {{pkgPathFor "core/php"}}/etc/php-fpm.d/www.conf

chmod +x {{pkg.svc_data_path}}
chown -R hab:hab {{pkg.svc_data_path}}

#hab svc load core/wordpress-proxy --group {{svc.group}} --force
