apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-toml
type: Opaque
data:
  # Each item needs to be base64-encoded.
  # Plain text content:
  #   app_username="wordpress"
  #   app_password="ThisIsSecret"
  #   app_database="wordpress"
  #   bind='0.0.0.0'
  user.toml: YXBwX3VzZXJuYW1lPSJ3b3JkcHJlc3MiCmFwcF9wYXNzd29yZD0iVGhpc0lzU2VjcmV0IgphcHBfZGF0YWJhc2U9IndvcmRwcmVzcyIKYmluZD0nMC4wLjAuMCcK
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-user-toml
type: Opaque
data:
  # nodbrestore = 'true'
  user.toml: bm9kYnJlc3RvcmUgPSAndHJ1ZSc=
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: wordpress-db
  labels:
    source: habitat-demo
    app: wordpress-habitat
customVersion: v1beta2
spec:
  v1beta2:
    image: alanwthatcher/mysql:5.7.17
    count: 1
    service:
      name: mysql
      topology: standalone
      configSecretName: mysql-user-toml
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: wordpress-app
  labels:
    source: habitat-demo
    app: wordpress-habitat
customVersion: v1beta2
spec:
  v1beta2:
    image: alanwthatcher/wordpress:4.9.9
    count: 1
    service:
      name: wordpress
      topology: standalone
      configSecretName: wordpress-user-toml
      bind:
        - name: database
          service: mysql
          group: default
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-lb
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    habitat-name: wordpress-app
