version: '2'
services:
  mysql:
    image: alanwthatcher/mysql:5.7.17
    environment:
      HAB_MYSQL: "bind = '0.0.0.0'\napp_username = 'wordpress'\napp_password = 'ThisIsPassword'\napp_database = 'wordpress'" 
    ports:
      - 9638:9638
  wordpress:
    image: alanwthatcher/wordpress:5.1
    command: --peer deploy_mysql_1 --bind database:mysql.default
    depends_on:
      - "mysql"
    ports:
      - 80:80